[Ready] Bone Anvil and processable Bone ingots
Citadel-Station-13/Citadel-Station-13 pull request #15290
Opened 2021-10-20 20:09 UTC by WanderingFox95

## About The Pull Request

Requested by @dzahlus and "the gang" which I think includes @keronshb and frankly a good next step for adding to the tribal crafting PR. You can now make an anvil out of bones (which has the same stats as the one cargo can order but is harder to make). You can also turn bones into ingots now, because why mine when you can bone?... okay, bad joke. But still. They're slightly more powerful than titanium, but not as good as adamantium.

## Why It's Good For The Game

It's only logical to extend the uses for bones, sinews and goliath hide further, right?

## Changelog
:cl:
add: bone anvils and bone ingots
imageadd: bone anvil sprites
/:cl:

2021-10-21 02:53 UTC, DeltaFire15 requested changes

2021-10-21 02:53 UTC, DeltaFire15 commented on code/modules/smithing/smithed_items.dm
> +	custom_materials = list(/datum/material/bone=12000)
Crafting recipe needs 2 bones, material value is effectively 6 bones. Change it to 4000 to avoid material duplication.

2021-10-21 02:53 UTC, DeltaFire15 commented on code/datums/materials/basemats.dm
> +	strength_modifier = 1.2
I have no idea how you alloy bones, or *smelt* them once that is somehow done, but if we look past however that works, it should probably be at base damage tier or only slightly above, definitely not over titanium.

2021-10-21 02:53 UTC, DeltaFire15 commented on code/datums/components/crafting/recipes/recipes_primal.dm
> +	tools = list(/obj/item/weldingtool/experimental/ashwalker, /obj/item/crowbar/ashwalker)
Kinda weird to have one of the strongest normally obtainable anvils be available for killing like four lavaland enemies total when the alternative is a pretty hefty cargo price. Then again, not strictly against it.

2021-10-21 08:25 UTC, WanderingFox95 commented on code/datums/components/crafting/recipes/recipes_primal.dm
> +	tools = list(/obj/item/weldingtool/experimental/ashwalker, /obj/item/crowbar/ashwalker)
Let's see... In total we have... 2 bones, 2 sinews, 1 regen core for the welding tool, 2 bones, 1 sinew for the crowbar, and then 4 bones, 2 sinews and 1 goliath hide for the anvil. That's 8 bones, 5 sinews, 1 core, 1 hide, 
3 Watchers, 3 Goliaths, 1 Legion. I can up it a little more though, that's not much of an issue.

2021-10-21 08:29 UTC, WanderingFox95 commented on code/datums/materials/basemats.dm
> +	strength_modifier = 1.2
You don't need to fight to get titanium so it feels like a downgrade to fight for the bones, isn't that kind of the opposite of the idea here?
The original idea was making it the opposite of gold, but I did not find a speed stat for gold and couldn't give one to the bones.

2021-10-21 08:30 UTC, WanderingFox95 commented on code/modules/smithing/smithed_items.dm
> +	custom_materials = list(/datum/material/bone=12000)
This one's fair.

2021-10-21 22:14 UTC, DeltaFire15 requested changes
All good otherwise imo now.

2021-10-21 22:14 UTC, DeltaFire15 commented on code/datums/components/crafting/recipes/recipes_primal.dm
> +	tools = list(/obj/item/weldingtool/experimental/ashwalker, /obj/item/clothing/gloves/tackler/combat/goliath)
Needing tackler gloves as tool for it just seems weird, feel free to return it to the crowbar or some other simillar tool (maybe just slightly more bone instead?)

2021-10-21 22:18 UTC, WanderingFox95 commented on code/datums/components/crafting/recipes/recipes_primal.dm
> +	tools = list(/obj/item/weldingtool/experimental/ashwalker, /obj/item/clothing/gloves/tackler/combat/goliath)
Added the cutters for the sinew-working, guess that makes more sense. And two more bones.

2021-10-25 15:59 UTC, DeltaFire15 commented on code/modules/mining/equipment/kinetic_crusher.dm
> -/obj/item/kinetic_crusher/glaive/bone/update_icon_state()
The fix PR that also did this got merged , might want to readd this so you don't accidentally revert it.

2021-10-25 16:11 UTC, DeltaFire15 approved these changes

2021-10-25 16:11 UTC, merged